### PR TITLE
bermudan swaption rewrite

### PR DESCRIPTION
**Pull request by tleitch**
Rewrite of bermudan code to allow more general structures. added are generalized maturity and swaption exercise dates versus previous hard coded. Leg parameters also made general and pay fix logical was fixed. Documentation also updated.

Affine swaption code based on this included but will be part of next pull along with unit tests for fixed income functions.

### CODE REVIEW

**Comment by tleitch** [comment]
I checked the fail and it is a test based on the old hardwired code taken from the Quantlib example. The example in the man file should run the same as the old, but the inputs have changed.

**Comment by eddelbuettel** [comment]
You also wrote in #38 (which we could have reopened...) that pull request should cover three files yet you submit twelve.  It would be nice if could straighten this out before pushing.

It might be a good idea to run `R CMD check` locally as well.   These failures reveal themselves this way, and it would have given you a chance to update the parameters accordingly.

**Comment by tleitch** [comment]
I'm reviewing the git documentation for RStudio. I do not understand what it is doing. I staged 3 files and the push failed due to files other than the 3 I was committing. I straightened it out (I thought) and committed and pushed. When I looked at it there were numerous conflicts and I had to unwind them by hand. Somewhere I staged more files, but I do not recall checking the box. Apologies.

**Comment by eddelbuettel** [comment]
I am sorry that this is so confusing.   I'd be happy to walk you through a short example via Google Hangout and screen sharing.  I'm home and open this evening.

The Git site also lists a number of [other GUIs](https://git-scm.com/download/gui/linux).  Might be worth a poke.  I hear the one by GitHub is ok.  I swear by Emacs' magit mode but that is just me...

**Comment by eddelbuettel** [comment]
But anyway -- git is just one part.  I think you want to become better at testing and not submitting code that does not build.

**Comment by eddelbuettel** [comment]
And we *will* get this working.   A good potential contributor with the mindset and patience to write swaptions code doesn't come along that often, so I am happy to cut you quite some slack and try to help as I can (while other things compete for my attention just as they do for yours).

**Comment by tleitch** [comment]
Thanks. I will take you up on the git session but I have a 5 a.m. train to NY returning at midnight, so maybe Friday or later. Yes, we will get through this. Looking forward to moving on to volcube and CDS eventually.

**Pull request closed without merging**
