### PR TITLE
Bermudan & Affine swaption submission

### PR DESCRIPTION
**Pull request by tleitch**
Bermudan and Affine code and examples were rewritten. Search is limited to 5 market swaption vols for fit with the 1st swaption being the closest to the initial exercise date.

### CODE REVIEW

**Comment by tleitch** [comment]
Eliminated all warnings. Code is set up to run base case in BermudanSwaption example. BermudanSwaption will take either market quotes or a DiscountCurve. AffineSwaption will only take a DiscountCurve. AffineSwaption will do a European swaption or Bermudan, but both are valued using an affine rate model that is fit to a vol curve.

**Comment by eddelbuettel** [comment]
I only had a chance to glance at this so far but I haven't seen any reason not to merge....

**Comment by eddelbuettel** [comment]
Merged.

We still need to fill in ChangeLog and inst/NEWS.Rd -- can you draft something (incl preferred email address for you) and just post it here?

**Comment by tleitch** [comment]
Will do.

From:  Dirk Eddelbuettel <notifications@github.com>
Reply-To:  eddelbuettel/rquantlib
<reply+007042a295b2feb10ba7bf58c9c5be06ce1f9cf53fd60e7992cf000000011348f0029
2a169ce092ac567@reply.github.com>
Date:  Monday, May 9, 2016 at 8:40 PM
To:  eddelbuettel/rquantlib <rquantlib@noreply.github.com>
Cc:  terry leitch <tleitch@uchicago.edu>, Author <author@noreply.github.com>
Subject:  Re: [eddelbuettel/rquantlib] Bermudan & Affine swaption submission
(#43)


Merged.

We still need to fill in ChangeLog and inst/NEWS.Rd -- can you draft
something (incl preferred email address for you) and just post it here?


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/eddelbuettel/rquantlib/pull/43#issuecomment-218029951>

**Comment by tleitch** [comment]
ChangeLog:

2016-05-09  Terry Leitch  <tleitch1@jhu.edu>

    * NAMSPACE: Updated to refelct new methods for affine swaption
    * R/affine.R: New generic swaption model based on bermudan affine model
    * R/bermudan.R: Swaption model modified to take more general tenor & expiration dates and curve input
    * src/affine.cpp: New engine for affine swaption model
    * src/bermudan.cpp: Swaptions for fit selection & yield curve fit moved up into bermudan.R
    * man/AffineSwaption.Rmd: created
    * man/BermudanSwaption.Rmd: Modified to reflect DiscountCurve option and example updated
    

NEWS.Rmd:

\section{Changes in RQuantLib version 0.4.3 (2016-06-30)}{
  \itemize{
    \item Changes in RQuantLib code:
    \itemize{
      \item BermudanSwaption has been modfied to take option expiration and swap tenors in order to
      enable more general swaption structure pricing. A more general search for the swaptions was 
      developed to accomodate this. Also, a DiscountCurve is allowed as an alternative to market 
      quotes to reduce computation time for a portfolio on a given valuation date. 
      \item A parallel model to BermudanSwaption, AffineSwaption, was developed and has similar interface 
      to BermudanSwaption but it allows for valuation of a European exercise swaption valutaion utlizing 
      the same affine methods available in BermudanSwaption. AffineSwaption will also value a Bermudan 
      swaption, but it does not take rate market quotes to build 
      a term structure. A DiscountCurve object is required.(contributed by Terry Leitch in \ghpr{41})
    }
  }
}

**Comment by eddelbuettel** [comment]
Thank you.  From the look of it, you seem to have one more closing curly than opening.  That would upset parsing, and `R CMD check` -- which you surely ran, right? RIGHT?  ;-) -- would have told you too.

I'll fold that in.

**Comment by eddelbuettel** [comment]
As for email, it is now jhu, it was uchicago before.  Do you prefer one over the other?

**Comment by tleitch** [comment]
Yes, want to move to jhu email as it has better filters which is good when
facing the public.

From:  Dirk Eddelbuettel <notifications@github.com>
Reply-To:  eddelbuettel/rquantlib
<reply+007042a259a36985eee09489ad8be42e6134bb8e633b192c92cf00000001134c9d2e9
2a169ce092ac567@reply.github.com>
Date:  Thursday, May 12, 2016 at 3:36 PM
To:  eddelbuettel/rquantlib <rquantlib@noreply.github.com>
Cc:  terry leitch <tleitch@uchicago.edu>, Author <author@noreply.github.com>
Subject:  Re: [eddelbuettel/rquantlib] Bermudan & Affine swaption submission
(#43)


As for email, it is now jhu, it was uchicago before.  Do you prefer one over
the other?


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/eddelbuettel/rquantlib/pull/43#issuecomment-218862737>

**Comment by eddelbuettel** [comment]
I'll update accordingly.

**Comment by eddelbuettel** [comment]
Now committed in 0660070a47f27f40f66afbe42467e12769009416

**Pull request merged**
