### PR TITLE
update news & change log drafts

### PR DESCRIPTION
**Pull request by tleitch**
Draft. Not sure I understand versioning, so left as is from before.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I am closing this. I really do not have the time to baby sit yet another wave of failed merges. Recall that I suggested [here](https://github.com/eddelbuettel/rquantlib/pull/43#issuecomment-218029951) in #43 to 

>  just post it here?

as it i faster for me to just copy and paste your stuff.

**Comment by tleitch** [comment]
ChangeLog:

2016-05-09  Terry Leitch  <tleitch1@jhu.edu>

    * NAMSPACE: Updated to refelct new methods for affine swaption
    * R/affine.R: New generic swaption model based on bermudan affine model
    * R/bermudan.R: Swaption model modified to take more general tenor &
expiration dates and curve input
    * src/affine.cpp: New engine for affine swaption model
    * src/bermudan.cpp: Swaptions for fit selection & yield curve fit moved
up into bermudan.R
    * man/AffineSwaption.Rmd: created
    * man/BermudanSwaption.Rmd: Modified to reflect DiscountCurve option and
example updated
    

NEWS.Rmd:

\section{Changes in RQuantLib version 0.4.3 (2016-06-30)}{
  \itemize{
    \item Changes in RQuantLib code:
    \itemize{
      \item BermudanSwaption has been modfied to take option expiration and
swap tenors in order to
      enable more general swaption structure pricing. A more general search
for the swaptions was
      developed to accomodate this. Also, a DiscountCurve is allowed as an
alternative to market
      quotes to reduce computation time for a portfolio on a given valuation
date. 
      \item A parallel model to BermudanSwaption, AffineSwaption, was
developed and has similar interface
      to BermudanSwaption but it allows for valuation of a European exercise
swaption valutaion utlizing
      the same affine methods available in BermudanSwaption. AffineSwaption
will also value a Bermudan
      swaption, but it does not take rate market quotes to build
      a term structure. A DiscountCurve object is required.(contributed by
Terry Leitch in \ghpr{41})
    }
  }
}


From:  Dirk Eddelbuettel <notifications@github.com>
Reply-To:  eddelbuettel/rquantlib
<reply+007042a29091ae7dcfcb82158a3c491905f3ec27a423890a92cf00000001134c97d09
2a169ce09364fef@reply.github.com>
Date:  Thursday, May 12, 2016 at 3:13 PM
To:  eddelbuettel/rquantlib <rquantlib@noreply.github.com>
Cc:  terry leitch <tleitch@uchicago.edu>, Author <author@noreply.github.com>
Subject:  Re: [eddelbuettel/rquantlib] update news & change log drafts (#45)


I am closing this. I really do not have the time to baby sit yet another
wave of failed merges. Recall that I suggested here
<https://github.com/eddelbuettel/rquantlib/pull/43#issuecomment-218029951>
in #43 <https://github.com/eddelbuettel/rquantlib/pull/43>  to
> 
> just post it here?

as it i faster for me to just copy and paste your stuff.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/eddelbuettel/rquantlib/pull/45#issuecomment-218856959>

**Comment by eddelbuettel** [comment]
Looks like the build failure had nothing to do with you ... but is the '10 minutes with no stdout' limit on Travis.  Not sure how to overcome that.

**Comment by eddelbuettel** [comment]
There: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by tleitch** [comment]
I was surprised on the fail, but I did forget to do R CMD check. My brain is
fried from an all night Tuesday debug/performance on software that went live
today.

From:  Dirk Eddelbuettel <notifications@github.com>
Reply-To:  eddelbuettel/rquantlib
<reply+007042a294ec99e8d0399606f09c9e1585e5894c4e11269192cf00000001134ca9b59
2a169ce09364fef@reply.github.com>
Date:  Thursday, May 12, 2016 at 4:29 PM
To:  eddelbuettel/rquantlib <rquantlib@noreply.github.com>
Cc:  terry leitch <tleitch@uchicago.edu>, Author <author@noreply.github.com>
Subject:  Re: [eddelbuettel/rquantlib] update news & change log drafts (#45)


Looks like the build failure had nothing to do with you ... but is the '10
minutes with no stdout' limit on Travis.  Not sure how to overcome that.


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/eddelbuettel/rquantlib/pull/45#issuecomment-218876311>

**Comment by eddelbuettel** [comment]
I just checked `git log .travis.yml` and I did have that on at one point.  I'll turn it back on. As I recall, it makes the output kinda ugly but _c'est la vie_

Apologies for barking earlier.  You had not broken the build, we are simply close to limits here.

(And you did have spelling mistakes :)  but I am not one to talk either.)

**Pull request closed without merging**
