### PR TITLE
SabrSwaption doc + reshape2 dependence eiliminated

### PR DESCRIPTION
**Pull request by tleitch**
Followed the outline you provided. There is one warning in travis for the data documentation for which rqlib.R  is intended to be an rooxygen2 document for the data, but I was unable to get roxygen2 to recognize it.

Overall, no other issues that have been flagged in R CMD check or travis.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Very exciting -- this look very clean (just five files) and precisely how we want to do this.  No merge conflicts either.  

And the `R CMD check` is very clean.  There is one technical one which I now have a way to suppress at source:

```
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘travis_wait_2198.log’
* checking for left-over files ... OK
```

so that will be a non-issue, and the remaining missing documentation should be simple:

```
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘tsQuotes’ ‘vcube’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... OK
```

Maybe just two additional aliases in the file `rqlib.R` you already added.

Very, very nice.  Well done, Terry!

**Comment by eddelbuettel** [comment]
So I merged this.  Try to have your local checkout of your fork catch-up.  You may need something like
adding a tracking master.  From my old local README (and adapted)

#### add a tracking master (cf https://help.github.com/articles/adding-a-remote)
        git remote add --track master parentrepo https://github.com/eddelbuettel/rquantlib.git

after which `git pull --all` and `git merge parentrepo` should get up to speed.  `git log` should then show my merge commit on top of all your fine work.

**Comment by tleitch** [comment]
Thanks. I believe I have in synch and understand....better. Slow learner on this. I see in rstudio I have a "master" and a "eddelbuettel/master" and they are in synch. I write in master, push to my github, and when ready, pull.

**Comment by eddelbuettel** [comment]
RStudio is "just" an editing tool / IDE -- it's git support is very basic.

I would recommend getting friendly with a dedicated IDE for git.  There [are many to choose from](https://git-scm.com/download/gui/linux). I am partial to Emacs' magit mode; but some of the GUIs can be nice.

And command-line is invaluable. I have some useful aliases and bash tricks.  Happy to share but your YMMV.

**Comment by eddelbuettel** [comment]
I got the data stuff sorted out. See commit https://github.com/eddelbuettel/rquantlib/commit/1106ee33becec3df313f2969b8b36d052e112c5e for details.  PR coming in a moment.  Make sure you pull that in once it hits master.

**Pull request merged**
