### PR TITLE
Conflicts resolved

### PR DESCRIPTION
**Pull request by tleitch**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I am really sorry Terry but this seems to be a regression.  

See eg the [Travis log here](https://travis-ci.org/eddelbuettel/rquantlib/builds/148203746) -- I got the same results by hand.   Copying and pasting from my local test:

```
* checking R code for possible problems ... NOTE
volDF2CubeK: warning in factor(tbl$Expiry, level = expLvl): partial
  argument match of 'level' to 'levels'
volDF2CubeK: warning in factor(tbl$Tenor, level = tenorLvl): partial
  argument match of 'level' to 'levels'
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘tsQuotes’ ‘vcube’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R Extensions’ manual.
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'SabrSwaption':
SabrSwaption
  Code: function(params, ts, volCubeDF, legparams = list(dayCounter =
                 "Thirty360", fixFreq = "Annual", floatFreq =
                 "Semiannual"), tsUp01 = NA, tsDn01 = NA, vega = FALSE)
  Docs: function(params, ts, vcube, swaplegparams)
  Argument names in code not in docs:
    volCubeDF legparams tsUp01 tsDn01 vega
  Argument names in docs not in code:
    vcube swaplegparams
  Mismatches in argument names:
    Position: 3 Code: volCubeDF Docs: vcube
    Position: 4 Code: legparams Docs: swaplegparams

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'SabrSwaption'
  ‘vcube’ ‘swaplegparams’
Documented arguments not in \usage in documentation object 'SabrSwaption':
  ‘dv01Up=NA’ ‘dv01Dn=NA’ ‘vega=FALSE’ ‘volCubeDF’ ‘legparams’

Functions with \usage entries need to have the appropriate \alias entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
```

The very first is what I fixed after your PR #60, and now it seems to have reverted.  I am obviously not all that excited about re-fixing it. 

Can we do better?  Can we/shall we maybe discuss process and try smaller individual steps here rather than deleting entire PRs yet coming back with ones comprising dozens of commits?

The ideal PR would add new features, be complete in terms of documentation and tests and not raise any issue with `R CMD check` all of which you should be able to see at your end.

Let me know how you want to go about this. Happy to chat on the video or per video call, time permitting.  I am sure we can get this fixed if we put our heads to it.

**Comment by eddelbuettel** [comment]
```
* checking R code for possible problems ... NOTE
volDF2CubeK: warning in factor(tbl$Expiry, level = expLvl): partial
  argument match of 'level' to 'levels'
volDF2CubeK: warning in factor(tbl$Tenor, level = tenorLvl): partial
  argument match of 'level' to 'levels'
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... NOTE
Rd file 'SabrSwaption.Rd':
  \usage lines wider than 90 characters:
     SabrSwaption(params, ts, volCubeDF, legparams = list(dayCounter = "Thirty360", fixFreq = "Annual", floatFreq = "Semiannual"), tsUp01 =  ... [TRUNCATED]
These lines will be truncated in the PDF manual.
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented data sets:
  ‘tsQuotes’ ‘vcube’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
```

**Comment by tleitch** [comment]
Several issues. This was not supposed to go to you yet. I followed a tutorial on merging from the master and now I have several branches on my machine and lost commits, so yes, any time you can spare for me would be appreciated.

**Comment by eddelbuettel** [comment]
Here is what I would do:

- Rename your current directory to `RQuantLib-old` or some other name.
- Possibly also rename your existing fork.
- Start clean.  Fork my master into your repo.
- Clone it locally, ie have a local copy.
- Look 'git log'.  It should be same as my public github.
- Run eg `git checkout -b feature/first-change` (or some other name)
- Make one or two targeted commits.  Something simple -- like the change to `DESCRIPTION` and `NAMESPACE` regarding zoo.
- Commit.  Push to your fork at GitHub.
- This should result in several things:
   + You being a one two commits ahead, so it should offer you a clean and comprehensible PR not consisting of a waterfall of a dozen or more commits
   + It should run Travis, and you should get a squeaky clean `R CMD check` from Travis
- If so, create a clean PR I can review.

Then rinse repeat in small self-contained portions til we're done.

**Pull request closed without merging**
