### PR TITLE
MacOS: update to univeral build of quantlib 1.13.1

### PR DESCRIPTION
**Pull request by jeroen**
This updates the "fallback" libquantlib+boost to the new universal bundles. This is more robust for cross compiling from intel to arm, because the same bundle can be used for either architecture.

### CODE REVIEW

**Review by eddelbuettel — APPROVED** [review]
Thanks looks good to me.  Thanks for the assist, much appreciated. 

Feel free to add yourself to ChangeLog too if you want, I can wait a moment or three with the merge.

**Comment by jeroen** [comment]
Go ahead and merge it, I have some enough other things to fix :)

**Comment by eddelbuettel** [comment]
I can always add you in locally here and commit after the merge.

**Comment by eddelbuettel** [comment]
Minor type in your commit message:  1.31.1, not 1.13.1

**Pull request merged**
