### PR TITLE
Feature/update diveqopt

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by hfty** [comment]
Thanks for the clean-up, that looks great to me. The Nullable thing is much better – previous interface was segfaulting if you were not providing a vector, I found out.

**Comment by eddelbuettel** [comment]
Ah, yes, I can see that.  What you had was "workable" but I guess you needed test for `length(x) > 0` rather than `x[0] == 0` which also places some weird constraints on content.

`Nullable<>()` is pretty slick, I like it.  It only ever works with the instantiated type, and you still need to create it.  Which here means for the dividens:  `Rcpp::NumericVector` only to then copy to `std::vector<...>`.  Oh well.

Would you be interested in noodling with actual dates?  We _can_ pass R `Date` (and now `Datetime`) objects to `QuantLib::Date`.  I wouldn't mind seeing if we can narrow the pricing error down that way.

**Comment by hfty** [comment]
Sure. I think I first need to track down a few more examples from books (which is harder than expected!) for a benchmark. Or I could use the DerivaGem spreadsheet from Hull to generate some, what do you think? Looks like he uses a binomial tree. Ideally we would look for examples using the same methodology, but...

**Comment by eddelbuettel** [comment]
Agreed that it is hard.  I hand-copied from or two from my old copy of Hull.   We also have the QL examples and tests, of course -- re-testing ensures that we didn't introduced errors in mapping parameters etc pp and is also valuable.

Regarding different pricing methods: good point. That could drive quite some differences.  Ideally we would want close values on comparables.  The 1e-1 and 1e-2 irritate me out a little because it is widest we have used, I think.  But I haven't look in detail.  It could all be a for a good reason.

**Comment by hfty** [comment]
Well, my understanding is that the binomial tree/non-recombining lattice of Hull should get us pretty close, should it not? But the Roll-Geske-Whaley approximation could be pretty far off. This may me [a pretty good summary](http://www.finanzaonline.com/forum/attachments/econometria-e-modelli-di-trading-operativo/1390259d1298451714-qualche-idea-per-una-tesi-odd.pdf) and it has a few examples. I'm going to look at how we fare compared to their examples.

**Pull request merged**
