### PR TITLE
 Inline as/wrap functions, include them in RQuantLib.h #183

### LINKED ISSUE #182: Duplicate symbol error when using RQuantLib in a package
First of all, thank you so much for your work on this amazing package! I'm currently trying to use in an internal package for the company I work at, but I'm stumbling on the following problem. 

My goal is to have the interfaces for C++ functions taking in or returning QuantLib date types be automatically generated (much like they are for Armadillo classes with Rcpp).  However, the master header file `RQuantLib.h` does not include the wrapper functionality implemented in `rquantlib_impl.h` by default. When I try to force it by passing `-DRQuantLib_Plugin` in my Makevars, the linker complains about "duplicate symbols".

I think the issue is caused by the fact that the templates for `as` and `wrap` are not marked `inline` and thus are put separately in all the object files which use the header (I will try to clone the repo to verify this once I get home this evening). In the mean time, I'm doing

```{cpp}
#include <rquantlib_impl.h>
#include <rquantlib_internal.h>
```

but that doesn't seem to me to follow best practices. Have you encountered this difficulty before?

### PR DESCRIPTION
**Pull request by OthmanElHammouchi**
Closes #182

### CODE REVIEW

**Comment by eddelbuettel** [comment]
What's different between this #184 and the #183 you close?

**Comment by eddelbuettel** [comment]
I'll take a look at the failing CI in a bit.  I use the same setup all the time, and can run this locally here on Ubuntu.  Not to worry yet.

**Comment by eddelbuettel** [comment]
CI job runs fine here, error was clearly a timeout at https://launchpad.net from where I source an update QuantLib (from my own PPA I host there).  So restarted one more more time.

**Comment by eddelbuettel** [comment]
Boooh.  And then macOS got in the way.  I commented that out now.  (I get to commit back to your PR repo by default as the re[o owner of the repo you sent a PR to.)

**Comment by eddelbuettel** [comment]
Merged (and then increased micro-released).  We will see in about an hour what [r-universe](https://eddelbuettel.r-universe.dev/RQuantLib) thinks about the mac build. Jeroen has helped at time getting libquantlib updated.

**Comment by OthmanElHammouchi** [comment]
If necessary I can also take a look at it on my work Mac machine tomorrow (my personal setup is Debian).

**Comment by eddelbuettel** [comment]
The trick is to provide a current enough pre-made library that CRAN and/or r-universe can use. I keep forgetting the details but I will keep that offer in mind :)

**Comment by eddelbuettel** [comment]
Yeah, went belly-up too:

image

Not sure how familiar you are with debugging GitHub Actions but the log is here:
   https://github.com/r-universe/eddelbuettel/actions/runs/8367163285
We can ignore the :x: on web-assembly (missing library) but the two macOS fails need help. Or else we fall back to 'work on Linux'.

**Comment by eddelbuettel** [comment]
It may be something simple. I was able to drill down to the 00install.out and it appers we redefine `BOOST_NO_AUTO_PTR`

image

**Comment by eddelbuettel** [comment]
Maybe we just no longer need it.  QuantLib changed internally a while back and may now automagically switch from it.  Seems to build fine for me here without it.

**Comment by eddelbuettel** [comment]
Ok -- now it gets further and then dies on your changes:

image

So something is happening specifically on macOS.  I can try tomorrow on Linux with clang++ to see if that makes a difference.

**Comment by eddelbuettel** [comment]
As it stands, I will need to revert #184 and have #185 ready.  I will try to make some time for your RQuantLibExamples packages to see how we can do what it wants to do with current RQuantLib, including dates.

**Comment by eddelbuettel** [comment]
I should add that it is entirely possible that i am doing one or more bone-headed things in the repo, but changing and improving those cannot come at the cost of removing existing functionality.

**Comment by OthmanElHammouchi** [comment]
I think I may have found where the issue arises. It seems that the plugin system does not automatically include the RQuantLib.h when you `sourceCpp`. Below is a snapshot of the files just before `sourceCpp` compiles them. For RQuantLib, the header is not included, however it is in the case of RcppArmadillo.

```cpp
// /tmp/RtmpxfBhpF/sourceCpp-x86_64-pc-linux-gnu-1.0.12/sourcecpp_10c261c72db45/breaking_example.cpp
#include <ql/quantlib.hpp>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  QuantLib::Date newYearsEve(31, QuantLib::Dec, 2008);
  QuantLib::Rate zc3mQuote = x;
  return zc3mQuote * 2;
}

// [[Rcpp::export]]
QuantLib::Date dateInDays(int n) {
    QuantLib::Date today = QuantLib::Date::todaysDate();
    QuantLib::Date res = today + n;
    return res;
}



#include <Rcpp.h>
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// timesTwo
double timesTwo(double x);
RcppExport SEXP sourceCpp_1_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// dateInDays
QuantLib::Date dateInDays(int n);
RcppExport SEXP sourceCpp_1_dateInDays(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(dateInDays(n));
    return rcpp_result_gen;
END_RCPP
}
```

```cpp
// /tmp/RtmpxfBhpF/sourceCpp-x86_64-pc-linux-gnu-1.0.12/sourcecpp_10c2617199c93/rcpp_armadillo.cpp
#include <ql/quantlib.hpp>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  QuantLib::Date newYearsEve(31, QuantLib::Dec, 2008);
  QuantLib::Rate zc3mQuote = x;
  return zc3mQuote * 2;
}

// [[Rcpp::export]]
QuantLib::Date dateInDays(int n) {
    QuantLib::Date today = QuantLib::Date::todaysDate();
    QuantLib::Date res = today + n;
    return res;
}
```

Is this behaviour expected? It's my first time digging into the Rcpp source code, so I may be completely off the mark here :sweat_smile:

**Comment by OthmanElHammouchi** [comment]
I think I may have found where the issue arises. It seems that the plugin system does not automatically include the RQuantLib.h when you `sourceCpp`. Below is a snapshot of the files just before `sourceCpp` compiles them. For RQuantLib, the header is not included, however it is in the case of RcppArmadillo.

```cpp
// /tmp/RtmpxfBhpF/sourceCpp-x86_64-pc-linux-gnu-1.0.12/sourcecpp_10c261c72db45/breaking_example.cpp
#include <ql/quantlib.hpp>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  QuantLib::Date newYearsEve(31, QuantLib::Dec, 2008);
  QuantLib::Rate zc3mQuote = x;
  return zc3mQuote * 2;
}

// [[Rcpp::export]]
QuantLib::Date dateInDays(int n) {
    QuantLib::Date today = QuantLib::Date::todaysDate();
    QuantLib::Date res = today + n;
    return res;
}



#include <Rcpp.h>
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// timesTwo
double timesTwo(double x);
RcppExport SEXP sourceCpp_1_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// dateInDays
QuantLib::Date dateInDays(int n);
RcppExport SEXP sourceCpp_1_dateInDays(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(dateInDays(n));
    return rcpp_result_gen;
END_RCPP
}
```

```cpp
// /tmp/RtmpxfBhpF/sourceCpp-x86_64-pc-linux-gnu-1.0.12/sourcecpp_10c2617199c93/rcpp_armadillo.cpp
#include <RcppArmadillo.h>
using namespace Rcpp;
// [[Rcpp::export]]
arma::vec test(arma::vec a) {
    return 2 * a;
}

#include <Rcpp.h>
#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test
arma::vec test(arma::vec a);
RcppExport SEXP sourceCpp_7_test(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(test(a));
    return rcpp_result_gen;
END_RCPP
}
```

Is this behaviour expected? It's my first time digging into the Rcpp source code, so I may be completely off the mark here :sweat_smile:

**Comment by OthmanElHammouchi** [comment]
Ok, so I've been digging through the code of Rcpp to try and understand what's happening here (first time so I am probably clueless :sweat_smile:). There is something I don't understand however: when you look at the example on the (RcppArmadillo page)[https://github.com/RcppCore/RcppArmadillo], it doesn't compile without header inclusions either. And if you add an '#include <RQuantLib.h>' at the top of your problem example, `sourceCpp` works fine for me.

So am I to understand that there has been a change in how you look at `[[Rcpp::depends]]` in between the two packages? Or is there some principled difference between the two usages? In any case, I understand that the example above still needs to work regardless, I'm trying to dig and see if that's possible.

**Comment by eddelbuettel** [comment]
I am with you. Something is not right.  It does not help that the initial datetime code in Rcpp was crap (mine :-) ) and the initial Date conversion in RQuantLib was not great either.

I seem to recall carrying local help functions around in user repos.  That is a shortcut.  Medium term we should of course fix that.  Here and/or in Rcpp.  I am little tied up but count on me.

First step though may be to 'just' unblock RQuantlibExamples.

**Comment by OthmanElHammouchi** [comment]
But what counts as unblocking? Do we want to be able to `sourceCpp` the example above? Because in that case my question would be: why don't we expect that in the case of RcppArmadillo? The code

```cpp
// [[Rcpp::export]]
arma::vec test(arma::vec v) {
    return 2 * v;
}
```

does not work for me with `sourceCpp`, I need to add '#include <RcppArmadillo.h>'. As far as I am able to understand, the fundamental  problem with the example is that it wants to use the wrapping functionality while relying purely on attributes, right?  Separately, there is no problem. If I add a file 'inline_example.cpp' with the code

```
#include <ql/quantlib.hpp>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::depends(RQuantLib)]]

// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  QuantLib::Date newYearsEve(31, QuantLib::Dec, 2008);
  QuantLib::Rate zc3mQuote = x;
  return zc3mQuote * 2;
}
```
I can `sourceCpp` it and the package compiles without problem.

**Comment by OthmanElHammouchi** [comment]
But what counts as unblocking? Do we want to be able to `sourceCpp` the example above? Because in that case my question would be: why don't we expect that in the case of RcppArmadillo? The code

```cpp
// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::export]]
arma::vec test(arma::vec v) {
    return 2 * v;
}
```

does not work for me with `sourceCpp`, I need to add '#include <RcppArmadillo.h>'. As far as I am able to understand, the fundamental  problem with the example is that it wants to use the wrapping functionality while relying purely on attributes, right?  Separately, there is no problem. If I add a file 'inline_example.cpp' with the code

```
#include <ql/quantlib.hpp>
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::depends(RQuantLib)]]

// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  QuantLib::Date newYearsEve(31, QuantLib::Dec, 2008);
  QuantLib::Rate zc3mQuote = x;
  return zc3mQuote * 2;
}
```
I can `sourceCpp` it and the package compiles without problem.

**Comment by eddelbuettel** [comment]
We broke macOS builds as I showed you.

**Comment by OthmanElHammouchi** [comment]
Yeah that's still a bit of a mystery to me 😅

**Comment by OthmanElHammouchi** [comment]
Honestly I have never seen something like this. On Linux, the final .so contains the symbol, on MacOS it doesn't.

MacOS:

```
rquantlib git:(master)  nm --demangle src/RQuantLib.so | grep "Rcpp::as<QuantLib::Date>"
                 U QuantLib::Date Rcpp::as<QuantLib::Date>(SEXPREC*)
```

Debian:

```
RQuantLib git:(master) ✗ nm --demangle src/[RQuantLib.so](http://rquantlib.so/) | grep "Rcpp::as"
00000000002318d0 T QuantLib::Date Rcpp::as(SEXPREC*)
000000000011e30d t QuantLib::Date Rcpp::as(SEXPREC*) [clone .cold
```

I'll have another look at the compiler flags etc. to see if they are causing the problem. I think I also know how to have wrapping without any changes, but it's not pretty 😅  I'll test it tomorrow.

**Comment by eddelbuettel** [comment]
Agreed.  But it is also `gcc` vs `clang` (and I couldn't switch here as QL imposes openmp which my clang doesn't have :-/)

We definitely use this header include pattern in other places.  It may end up being something simple but for now we are blocked :-/ 

Also, looking at your demangling (good idea!) I think 'U' means 'not there'.  We may have to force an instantiation?

**Comment by OthmanElHammouchi** [comment]
@eddelbuettel I have an update for you! After a lot of digging (I *really* wasn't expecting this issue to be so complicated), I found that everything compiles without problems if you disable optimizations with "-O0". 

```
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RQuantLib)

...

** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RQuantLibExample)
/Library/Developer/CommandLineTools/usr/bin/make clean
rm -rf src/*.o
rm -rf src/*.so
➜  RQuantLibExample git:(master) ✗ radian
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Platform: aarch64-apple-darwin23.2.0 (64-bit)

r$> library(RQuantLibExample)

r$> dateInDays(3)
[1] "2024-03-26"

r$>


```

[Some people on SO are having similar problems](https://stackoverflow.com/questions/22972545/undefined-reference-with-clang-with-o2). I'm assuming that disabling optimizations in a release version is a no-go for you right? In that case I'll keep digging to see if clang can be made to exhibit the same behaviour in some other way (I don't know if it's worth bothering the devs about this?).

As for gcc, I did consider that avenue, but if I'm not mistaken "Writing R Extensions" prohibits you from assuming the presence of a particular toolchain on a user's machine. Moreover, the homebrew distribution of QuantLib (which is realistically what most Mac users will have installed, I think) is built with Clang as far as I am able to tell (you get a huge number of `undefined symbol` errors when building RQuantLib with gcc against homebrew QuantLib), hence that doesn't seem like a promising avenue.

**Comment by OthmanElHammouchi** [comment]
What we could do is disable optimizations only for the section giving problems, i.e.

```cpp
#ifdef __clang__
#pragma clang optimize off
#endif

    template <> inline QuantLib::Date as(SEXP dtsexp) {
        Rcpp::Date dt(dtsexp);
        return QuantLib::Date(static_cast<int>(dt.getDate()) + QLtoJan1970Offset);
    }

    template <> inline SEXP wrap(const QuantLib::Date &d) {
        double dt = static_cast<double>(d.serialNumber()); // QL::BigInteger can cast to double
        return Rcpp::wrap(Rcpp::Date(dt - QLtoJan1970Offset));
    }

    // non-intrusive extension via template specialisation
    template <> inline std::vector<QuantLib::Date> as(SEXP dtvecsexp) {
        Rcpp::DateVector dtvec(dtvecsexp);
        int n = dtvec.size();
        std::vector<QuantLib::Date> dates(n);
        for (int i = 0; i<n; i++){
#if RCPP_VERSION >= Rcpp_Version(0,12,8)
            //dates[i] = QuantLib::Date(static_cast<int>(dtvec[i]) + QLtoJan1970Offset);
            dates[i] = QuantLib::Date(static_cast<int>(Rcpp::Date(dtvec[i]).getDate()) + QLtoJan1970Offset);
#else
            dates[i] = QuantLib::Date(static_cast<int>(dtvec[i].getDate()) + QLtoJan1970Offset);
#endif
        }
        return dates;
    }

    // non-intrusive extension via template specialisation
    template <> inline SEXP wrap(const std::vector<QuantLib::Date> &dvec) {
        int n = dvec.size();
        Rcpp::DateVector dtvec(n);
        for (int i = 0; i<n; i++) {
            // QL::BigInteger can cast to double
            double dt = static_cast<double>(dvec[i].serialNumber());
            dtvec[i] = Rcpp::Date(dt - QLtoJan1970Offset);
        }
        return Rcpp::wrap(dtvec);
    }


#ifdef __clang__
#pragma clang optimize on
#endif

```

I just tested it on my MacOS machine and it compiles without issues (with "-O2" in the ~/.R/Makevars). Of course, you have to find it acceptable to lose the compiler optimizations on that section.

**Comment by eddelbuettel** [comment]
Good work.  I think that is related to what I hinted before in "We may have to force an instantiation?" above.  I think what you found (and other before you) seems to be that the compiler optimises the inlined template away for a tighter executable, but then the linker complains that the symbol is missing.

So what you have is a fine local fudge for now, it is not something we can ship in the package.  Fundamentally, I think we are still doing something wrong.

This isn't or shouldn't block you: you can copy the `as<>()` and `wrap()` stanzas over into your real-life example, I have done the same.  We still need to figure why our overall design is yet working.  (And sorry, I remain swamped between work and now on the weekend updating slides for class...)   

But let's not drop this.  Something is not quite right, and we should fix the riddle somehow.

**Pull request merged**
